services:
  ddb:
    build:
      context: ../src/dynamodb
      dockerfile: Dockerfile
    networks:
      - localcloud
    volumes:
      - ddb-data:/var/lib/scylla
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ddb-data:

networks:
  localcloud:
    external: true
