services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: localcloud
      MINIO_ROOT_PASSWORD: localcloud
      LOG_LEVEL: DEBUG
    command: server --console-address ":9001" /data
    volumes:
      - data:/data
    networks:
      - localcloud

volumes:
  data:
