services:
  esm:
    build:
      context: ../src/event-source-mapping
    restart: always
    volumes:
      - data:/data
    # ports:
    #   - 4566:4566
    environment:
      STORAGE_PATH: /data
      LOG_LEVEL: DEBUG
    networks:
      - localcloud
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
