services:
  s3:
    # image: minio/minio
    build:
      context: ../src/s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: localcloud
      MINIO_ROOT_PASSWORD: localcloud
      AWS_ENDPOINT_URL: http://api:4566
      LOG_LEVEL: DEBUG
    volumes:
      - data-s3:/data
    networks:
      - localcloud

volumes:
  data-s3:
