services:
  ddb:
    image: scylladb/scylla:2025.3
    command:
      - --smp 2
      - --memory 2G
      - --alternator-port=4700
      - --alternator-write-isolation=always
    ports:
      - "4700:4700"
    networks:
      - localcloud
    volumes:
      - ddb-data:/var/lib/scylla
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ddb-data:
